### ISSUE TITLE
The script does not work.

### ISSUE THREAD

**Issue by daddyploaie** [Im-Beast/its-Quizizzd#14]
Hi, i entered a quizizz game and I clicked inspect element, then console and pasted the second command, the one that does not start with javascript. I pressed enter and it said that you can close console now, special thanks and that code thing that I pressed enter again, left it unfilled. I closed the console and nothing happened. There were no answers being lit up or anything. I tried the bookmark version too, I made a bookmark, set the URL to the one with javascript this time, entered a game, pressed on the script, again it said you can close console now and special thanks and that thing with the code, but again, there were no answers being lit up or anything. So please, help me. Thanks!

**Comment by Jay4503** [comment]
Me too 😭

daddyploaie <notifications@github.com> 于 2020年12月9日周三 下午7:42写道：

**Comment by CrosserX** [comment]
you need to enter the pin of the game

**Comment by CrosserX** [comment]
@daddyploaie

**Comment by daddyploaie** [comment]
Hmm, ok ima try that

**Comment by JEBE02** [comment]
> you need to enter the pin of the game

Where i can get game pin ?

**Comment by CrosserX** [comment]
it is the code you enter to join the game

**Comment by Thetacoman110** [comment]
Can someone help me were to put the game pin
