### ISSUE TITLE
captcha 

### ISSUE THREAD

**Issue by 4ETH** [Im-Beast/its-Quizizzd#6]
mordzia, dało by sie pozbyć sie captchy?

**Comment by Zakaria-oss** [comment]
Why Captcha Is Hard See?

**Comment by 4ETH** [comment]
it's annoying to enter captcha every time

**Comment by Im-Beast** [comment]
da sie, bedzie usunieta po updacie do rozszerzenia

**Comment by AC6764** [comment]
Próbowałem 2 godziny temu i działało dobrze, teraz już nie działa, czy możesz rozwiązać problem jutro rano przed 8 rano

**Comment by AC6764** [comment]
HELLO, I can change the color of the correct answer, because it is in green but I would like it in light gray, and to be able to remove "check answer", since I have to take the test in class. Please contact me privately. I need it for tomorrow

kochmar.vladimir14@gmail.com

**Comment by 4ETH** [comment]
Typie, załóż nowy wątek (create new issue) I tam to napisz
