### ISSUE TITLE
Pin?

### ISSUE THREAD

**Issue by 5ETY** [Im-Beast/its-Quizizzd#7]
Hey, Im-Beast

I was wondering the deal with the new pin thing? 

Cool code btw!

**Comment by Zakaria-oss** [comment]
Whats It's Number Pin?

**Comment by newproject448** [comment]
i use the quiz code for pin number. it's work

**Comment by Zakaria-oss** [comment]
What's Number Is You Pin? Im-Beast

Pada tanggal Rab, 2 Des 2020 10.10, newproject448 <notifications@github.com>
menulis:

**Comment by Im-Beast** [comment]
no pin anymore

**Comment by AC6764** [comment]
HELLO, I can change the color of the correct answer, because it is in green but I would like it in light gray, and to be able to remove "check answer", since I have to take the test in class. Please contact me privately. I need it for tomorrow

kochmar.vladimir14@gmail.com
