### ISSUE TITLE
What's Number Pin?

### ISSUE THREAD

**Issue by Zakaria-oss** [Im-Beast/its-Quizizzd#8]
Hey Beast..
what's Your Number Pin?

**Comment by Im-Beast** [comment]
//pin removed

**Comment by AC6764** [comment]
HELLO, I can change the color of the correct answer, because it is in green but I would like it in light gray, and to be able to remove "check answer", since I have to take the test in class. Please contact me privately. I need it for tomorrow

kochmar.vladimir14@gmail.com

**Comment by 4ETH** [comment]
> //pin removed

no  właśnie nie removed
